# -*- coding: utf-8 -*-
{
    'name': 'OpenKard Research Support',
    'version': '10.0.0.0.0',
    'license': 'LGPL-3',
    'category': 'Education',
    "sequence": 3,
    'summary': 'Researche Manage Library',
    'complexity': "easy",
    'author': '',
    'website': '',
    'depends': ['openkard_core','openkard_item','base_action_rule'],
    'data': [
        'security/kd_research_security.xml',
        'security/ir.model.access.csv',
        'views/research_view.xml',
        'views/visit_view.xml',
        'views/case_view.xml',
        'views/result_view.xml',
        'views/item_line_view.xml',
        'views/visit_line_view.xml',
        'views/visitset_line_view.xml',
        'views/visitset_view.xml',
        'views/visitset_user_view.xml',
        'report/report_result_analysis.xml',
        'report/result_report_menu.xml',
        'wizard/result_report_wizard_view.xml',
        'menus/research_menu.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}
